/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Manga } from "./Manga";
import { MangaCountArgs } from "./MangaCountArgs";
import { MangaFindManyArgs } from "./MangaFindManyArgs";
import { MangaFindUniqueArgs } from "./MangaFindUniqueArgs";
import { DeleteMangaArgs } from "./DeleteMangaArgs";
import { MangaService } from "../manga.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Manga)
export class MangaResolverBase {
  constructor(
    protected readonly service: MangaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Manga",
    action: "read",
    possession: "any",
  })
  async _mangaItemsMeta(
    @graphql.Args() args: MangaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Manga])
  @nestAccessControl.UseRoles({
    resource: "Manga",
    action: "read",
    possession: "any",
  })
  async mangaItems(@graphql.Args() args: MangaFindManyArgs): Promise<Manga[]> {
    return this.service.mangaItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Manga, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Manga",
    action: "read",
    possession: "own",
  })
  async manga(
    @graphql.Args() args: MangaFindUniqueArgs
  ): Promise<Manga | null> {
    const result = await this.service.manga(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Manga)
  @nestAccessControl.UseRoles({
    resource: "Manga",
    action: "delete",
    possession: "any",
  })
  async deleteManga(
    @graphql.Args() args: DeleteMangaArgs
  ): Promise<Manga | null> {
    try {
      return await this.service.deleteManga(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
