/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Anime } from "./Anime";
import { AnimeCountArgs } from "./AnimeCountArgs";
import { AnimeFindManyArgs } from "./AnimeFindManyArgs";
import { AnimeFindUniqueArgs } from "./AnimeFindUniqueArgs";
import { DeleteAnimeArgs } from "./DeleteAnimeArgs";
import { AnimeService } from "../anime.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Anime)
export class AnimeResolverBase {
  constructor(
    protected readonly service: AnimeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "read",
    possession: "any",
  })
  async _animeItemsMeta(
    @graphql.Args() args: AnimeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Anime])
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "read",
    possession: "any",
  })
  async animeItems(@graphql.Args() args: AnimeFindManyArgs): Promise<Anime[]> {
    return this.service.animeItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Anime, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "read",
    possession: "own",
  })
  async anime(
    @graphql.Args() args: AnimeFindUniqueArgs
  ): Promise<Anime | null> {
    const result = await this.service.anime(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Anime)
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "delete",
    possession: "any",
  })
  async deleteAnime(
    @graphql.Args() args: DeleteAnimeArgs
  ): Promise<Anime | null> {
    try {
      return await this.service.deleteAnime(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
